### ISSUE TITLE
[AOF5] Client crashes when attempting to cast t with staff

### ISSUE THREAD

**Issue by KyleTheScientist** [gamma-delta/HexMod#275]
# Description

Both in multiplayer and single player worlds I can no longer cast with the staff without the game crashing. The crash occurs when I attempt to drag from one node to the next. This doesn't seem to be associated with any specific spells or actions as it even occurs in newly generated creative worlds where all I have is a staff.

The main error in the crash log is this:
```
Description: mouseDragged event handler

io.github.fablabsmc.fablabs.api.fiber.v1.exception.FiberConversionException: Invalid serialized value 0
	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.derived.ConfigType.toRuntimeType(ConfigType.java:113)
	at io.github.fablabsmc.fablabs.impl.fiber.tree.PropertyMirrorImpl.getValue(PropertyMirrorImpl.java:78)
	at at.petrak.hexcasting.fabric.FabricHexConfig$Client.gridSnapThreshold(FabricHexConfig.java:186)
	at at.petrak.hexcasting.client.gui.GuiSpellcasting.method_25403(GuiSpellcasting.kt:141)
	at net.minecraft.class_312.redirect$bep000$onGuiMouseDraggedPost(class_312.java:2665)
	at net.minecraft.class_312.method_1602(class_312.java:197)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1600(class_312.java:197)
	at net.minecraft.class_312.method_22689(class_312.java:164)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22688(class_312.java:164)
	at org.lwjgl.glfw.GLFWCursorPosCallbackI.callback(GLFWCursorPosCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1150)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

# Steps to Reproduce 

1. Start a creative world
2. Give yourself a staff
3. Right click 
4. Attempt to drag from one node to another

# Crash Report

[crash report.txt](https://github.com/gamma-delta/HexMod/files/9957395/crash.report.txt)

# GIF

![crash](https://user-images.githubusercontent.com/16724608/200471674-b6212eff-0768-4380-92b4-290ea66d4987.gif)

**Comment by KyleTheScientist** [comment]
Duplicate of https://github.com/gamma-delta/HexMod/issues/164

**Comment by KyleTheScientist** [comment]
Duplicate of https://github.com/gamma-delta/HexMod/issues/164
